
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compi1.sqlemulator.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 20;
  public static final int PUNTO = 9;
  public static final int CADENA = 27;
  public static final int MAYOR_IGUAL_QUE = 17;
  public static final int INSERTAR = 4;
  public static final int OR = 21;
  public static final int IGUAL = 14;
  public static final int DECIMAL = 26;
  public static final int MENOR_IGUAL_QUE = 18;
  public static final int ELIMINAR = 7;
  public static final int MAYOR_QUE = 15;
  public static final int PARENTESIS_R = 12;
  public static final int FILTRAR = 3;
  public static final int VALORES = 23;
  public static final int ASIGNAR = 6;
  public static final int COMA = 24;
  public static final int ACTUALIZAR = 5;
  public static final int MENOR_QUE = 16;
  public static final int PARENTESIS_L = 11;
  public static final int EOF = 0;
  public static final int ASTERISCO = 10;
  public static final int DIFERENTE = 19;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 22;
  public static final int EN = 8;
  public static final int ENTERO = 25;
  public static final int SELECCIONAR = 2;
  public static final int FIN_INSTRUCCION = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECCIONAR",
  "FILTRAR",
  "INSERTAR",
  "ACTUALIZAR",
  "ASIGNAR",
  "ELIMINAR",
  "EN",
  "PUNTO",
  "ASTERISCO",
  "PARENTESIS_L",
  "PARENTESIS_R",
  "FIN_INSTRUCCION",
  "IGUAL",
  "MAYOR_QUE",
  "MENOR_QUE",
  "MAYOR_IGUAL_QUE",
  "MENOR_IGUAL_QUE",
  "DIFERENTE",
  "AND",
  "OR",
  "IDENTIFICADOR",
  "VALORES",
  "COMA",
  "ENTERO",
  "DECIMAL",
  "CADENA"
  };
}

